name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  solution: './APITempoDIO/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Instal .Net SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'


- script: dotnet restore $(solution)
  displayName: 'Restore Solution'

- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Build Solution'

- script: dotnet test $(solution) --configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage"
  displayName: 'Test Solution'

- task: Docker@2
  inputs:
    containerRegistry: 'myacrdiobootcamp'
    repository: 'api-tempo-dio-bootcamp'
    command: 'buildAndPush'
    Dockerfile: './Dockerfile'

- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'my-azure-sc'
    appName: 'api-tempo-dio-bootcamp'
    imageName: 'myacrdiobootcamp.azurecr.io/api-tempo-dio-bootcamp:latest'
    containerCommand: ''